name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up CMake
      run: |
        mkdir build
        cd build
        cmake ..
        
    - name: Build
      run: |
        cmake --build build --config Release

    - name: Run tests
      run: |
        cd build
        ctest --output-on-failure
